services:
  - type: web
    name: croak-bot-proxy
    env: node
    rootDir: .                 # 👈 Project root as base
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
