services:
  - type: web
    name: croak-executor-backend
    env: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PRIVATE_KEY
        sync: false
      - key: WALLET
        sync: false
