services:
  - type: web
    name: croak-executor-backend
    env: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PRIVATE_KEY
        sync: false
      - key: WALLET
        sync: false
      - key: INFURA_API
        sync: false
      - key: BYBIT_API_KEY
        sync: false
      - key: BYBIT_API_SECRET
        sync: false
